### ISSUE TITLE
Add a fold panel bar

### ISSUE THREAD

**Issue by iwoithe** [GimelStudio/gswidgetkit#13]
Currently, the fold panel bar is inside of the Gimel Studio repo itself (so it needs to be moved). The API needs to change as well. Currently you have to set colours, icons etc. when configuring each instance of a fold panel bar. This should be combined into one class so that the following example can be used.

```python
self.main_layout = wx.BoxSizer(wx.VERTICAL)

fpb_layout = wx.BoxSizer(wx.VERTICAL)
# [Add widgets to fpb_layout]

fpb = FoldPanelBar(self, label="Hello World", expanded=False)
fpb.SetSizer(fpb_layout)

self.main_layout.Add(fpb)
```

**Comment by Correct-Syntax** [comment]
The Foldpanelbar is now in gswidgetkit
