### ISSUE TITLE
What does the cursor is suppose to do in Mac?

### ISSUE THREAD

**Issue by yasuomaidana** [GimelStudio/gswidgetkit#4]
Hi, I just recorded a video to show how demo.py behaves in a Mac pc
![what](https://user-images.githubusercontent.com/32581141/122441881-9e54c680-cf63-11eb-8635-d31096a62313.gif)
When I click the bar to update its value, the cursor disappear. Is that ok?
Additionally there is an issue related to recursion error, I'll keep working on that.

**Comment by Correct-Syntax** [comment]
Yes, the cursor should disappear. This was done more to avoid the mouse flickering that would happen if it was shown, though it is also following how the widget in Blender 3d behaves also.
